#!/bin/bash

address=$1
profile=$2

if [[ -z $address || -z $profile ]]; then
	echo "Usage: $(basename $0) <address> <profile>"
	exit 1
fi

tmpfile=$(mktemp)

cat <<EOF > ${tmpfile}
#!/bin/bash

cd /tmp
wget -q -O quickstart.tar.gz https://github.com/madvertise/quickstart/tarball/master
tar -xzf quickstart.tar.gz

cd madvertise-quickstart-*
exec ./quickstart ${profile}
EOF

cat ${tmpfile} | \
ssh -l root \
	-o "StrictHostKeyChecking no" \
	-o "UserKnownHostsFile /dev/null" \
	-o "GlobalKnownHostsFile /dev/null" \
	${address} \
	"bash -s"

rm -f ${tmpfile}
